INSERT INTO books (title, author, publication_year, description, genre)
VALUES
    ('Where the Crawdads Sing', 'Delia Owens', 2018, 'A novel about a young woman who is abandoned as a child and raised in the swamps of North Carolina.', 'Fiction'),
    ('The Silent Patient', 'Alex Michaelides', 2019, 'A psychological thriller about a woman who shoots her husband and then stops speaking.', 'Thriller'),
    ('The Nightingale', 'Kristin Hannah', 2015, 'A novel about two sisters in Nazi-occupied France during World War II.', 'Historical Fiction'),
    ('The Midnight Library', 'Matt Haig', 2020, 'A novel about a woman who finds herself in a library between life and death.', 'Fantasy'),
    ('The Vanishing Half', 'Brit Bennett', 2020, 'A novel about twin sisters who choose to live in two very different worlds, one black and one white.', 'Contemporary Fiction'),
    ('A Man Called Ove', 'Fredrik Backman', 2012, 'A heartwarming story about a grumpy yet loveable man whose world changes when a new family moves in next door.', 'Fiction'),
    ('The Book Thief', 'Markus Zusak', 2005, 'A novel set in Nazi Germany narrated by Death, about a young girl who steals books to share with others.', 'Historical Fiction'),
    ('Little Fires Everywhere', 'Celeste Ng', 2017, 'A novel about family dynamics and the clash between a picture-perfect family and a single mother.', 'Fiction'),
    ('Circe', 'Madeline Miller', 2018, 'A reimagining of the story of Circe, the enchantress from Homer’s Odyssey.', 'Fantasy'),
    ('The Alchemist', 'Paulo Coelho', 1988, 'A philosophical novel about a young Andalusian shepherd on a journey to find treasure.', 'Adventure'),
    ('To Kill a Mockingbird', 'Harper Lee', 1960, 'A classic novel about racial injustice in the Deep South, seen through the eyes of a young girl.', 'Classic Fiction'),
    ('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'A novel set in the Jazz Age, exploring themes of decadence, idealism, and excess.', 'Classic Fiction'),
    ('1984', 'George Orwell', 1949, 'A dystopian novel about a totalitarian regime that uses surveillance and mind control.', 'Dystopian'),
    ('Pride and Prejudice', 'Jane Austen', 1813, 'A classic novel about love and social class in 19th century England.', 'Romance'),
    ('The Catcher in the Rye', 'J.D. Salinger', 1951, 'A novel about a teenage boy’s alienation and rebellion against the adult world.', 'Classic Fiction'),
    ('Becoming', 'Michelle Obama', 2018, 'A memoir by the former First Lady of the United States.', 'Memoir'),
    ('Educated', 'Tara Westover', 2018, 'A memoir about a woman who grows up in a strict and abusive household in rural Idaho but escapes to learn about the wider world through education.', 'Memoir'),
    ('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 2011, 'A book about the history and impact of Homo sapiens.', 'History'),
    ('The Subtle Art of Not Giving a F*ck', 'Mark Manson', 2016, 'A counterintuitive approach to living a good life.', 'Self-Help'),
    ('Atomic Habits', 'James Clear', 2018, 'A book about building good habits and breaking bad ones.', 'Self-Help'),
    ('Thinking, Fast and Slow', 'Daniel Kahneman', 2011, 'A book about the two systems that drive the way we think.', 'Psychology'),
    ('Outliers: The Story of Success', 'Malcolm Gladwell', 2008, 'A book that explores the factors that contribute to high levels of success.', 'Business'),
    ('The Power of Habit', 'Charles Duhigg', 2012, 'A book about how habits work and how they can be changed.', 'Self-Help'),
    ('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010, 'The story of a woman whose cells were used for medical research without her knowledge.', 'Biography'),
    ('Quiet: The Power of Introverts in a World That Can''t Stop Talking', 'Susan Cain', 2012, 'A book about the value of introverts in society.', 'Psychology'),
    ('Steve Jobs', 'Walter Isaacson', 2011, 'The biography of Apple co-founder Steve Jobs.', 'Biography'),
    ('The Wright Brothers', 'David McCullough', 2015, 'A biography of the Wright brothers, who invented the first successful airplane.', 'Biography'),
    ('Into the Wild', 'Jon Krakauer', 1996, 'The story of Christopher McCandless, a young man who hiked into the Alaskan wilderness.', 'Adventure'),
    ('Born a Crime: Stories from a South African Childhood', 'Trevor Noah', 2016, 'A memoir by the comedian about growing up in South Africa during and after apartheid.', 'Memoir'),
    ('Grit: The Power of Passion and Perseverance', 'Angela Duckworth', 2016, 'A book about the power of persistence and resilience.', 'Self-Help');


INSERT INTO ratings (rating, book_id, username)
VALUES
    (3, (SELECT id FROM books WHERE title = 'Where the Crawdads Sing'), 'user1@example.com'),
    (4, (SELECT id FROM books WHERE title = 'Where the Crawdads Sing'), 'user10@example.com'),
    (5, (SELECT id FROM books WHERE title = 'Where the Crawdads Sing'), 'user2@example.com'),
    (2, (SELECT id FROM books WHERE title = 'Where the Crawdads Sing'), 'user5@example.com'),
    (4, (SELECT id FROM books WHERE title = 'The Silent Patient'), 'user1@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Nightingale'), 'user1@example.com'),
    (2, (SELECT id FROM books WHERE title = 'The Nightingale'), 'user10@example.com'),
    (1, (SELECT id FROM books WHERE title = 'The Nightingale'), 'user11@example.com'),
    (4, (SELECT id FROM books WHERE title = 'The Midnight Library'), 'user2@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Vanishing Half'), 'user3@example.com'),
    (2, (SELECT id FROM books WHERE title = 'The Vanishing Half'), 'user13@example.com'),
    (3, (SELECT id FROM books WHERE title = 'The Vanishing Half'), 'user11@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Vanishing Half'), 'user1@example.com'),
    (4, (SELECT id FROM books WHERE title = 'The Vanishing Half'), 'user5@example.com'),
    (4, (SELECT id FROM books WHERE title = 'The Vanishing Half'), 'user4@example.com'),
    (3, (SELECT id FROM books WHERE title = 'A Man Called Ove'), 'user4@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Book Thief'), 'user4@example.com'),
    (4, (SELECT id FROM books WHERE title = 'Little Fires Everywhere'), 'user4@example.com'),
    (3, (SELECT id FROM books WHERE title = 'Circe'), 'user5@example.com'),
    (1, (SELECT id FROM books WHERE title = 'Circe'), 'user1@example.com'),
    (3, (SELECT id FROM books WHERE title = 'Circe'), 'user4@example.com'),
    (5, (SELECT id FROM books WHERE title = 'Circe'), 'user2@example.com'),
    (4, (SELECT id FROM books WHERE title = 'The Alchemist'), 'user5@example.com'),
    (2, (SELECT id FROM books WHERE title = 'To Kill a Mockingbird'), 'user6@example.com'),
    (3, (SELECT id FROM books WHERE title = 'The Great Gatsby'), 'user6@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Subtle Art of Not Giving a F*ck'), 'user10@example.com'),
    (4, (SELECT id FROM books WHERE title = 'Atomic Habits'), 'user10@example.com'),
    (3, (SELECT id FROM books WHERE title = 'Thinking, Fast and Slow'), 'user10@example.com'),
    (2, (SELECT id FROM books WHERE title = 'Outliers: The Story of Success'), 'user11@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Power of Habit'), 'user12@example.com'),
    (4, (SELECT id FROM books WHERE title = 'The Immortal Life of Henrietta Lacks'), 'user12@example.com'),
    (3, (SELECT id FROM books WHERE title = 'Quiet: The Power of Introverts in a World That Can''t Stop Talking'),
     'user13@example.com'),
    (2, (SELECT id FROM books WHERE title = 'Steve Jobs'), 'user13@example.com'),
    (5, (SELECT id FROM books WHERE title = 'The Wright Brothers'), 'user14@example.com'),
    (5, (SELECT id FROM books WHERE title = 'Into the Wild'), 'user14@example.com'),
    (3, (SELECT id FROM books WHERE title = 'Born a Crime: Stories from a South African Childhood'), 'user15@example.com'),
    (1, (SELECT id FROM books WHERE title = 'Grit: The Power of Passion and Perseverance'), 'user15@example.com');
